name: Check if all required files are UTF-8

on: 
  [push, pull_request]

permissions:
  contents: read

jobs:
  utf8check:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/UTF8Check.yml@5e78d9c26dd9b1fd131ce69da7532dd5f82a8801
    with:
      file-extensions: 'R\|json\|md'  #File extension(s) to check separated by \| Examples:
                                      #R
                                      #R\|json
