name: Validate Evaluation Plan

on: 
  [push, pull_request]

permissions:
  contents: read

jobs:
  Validate-Evaluation-Plan:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/ValidateQualificationPlan.yml@5e78d9c26dd9b1fd131ce69da7532dd5f82a8801
    with:
      qualification-plan: 'Evaluation/Input/evaluation_plan.json'
